# Generated by Django 5.1.7 on 2025-03-31 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignQuiz',
        ),
    ]
