# Generated by Django 5.1.7 on 2025-03-31 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_signquizquestion_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Quiz Title')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.level')),
                ('questions', models.ManyToManyField(related_name='quizzes', to='adminapp.question')),
            ],
        ),
    ]
