# Generated by Django 5.1.7 on 2025-03-31 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_signquiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignQuiz',
        ),
    ]
