# Generated by Django 5.1.7 on 2025-03-31 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_delete_signquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.level')),
                ('questions', models.ManyToManyField(related_name='quizzes', to='adminapp.question')),
            ],
        ),
    ]
