# Generated by Django 5.1.7 on 2025-03-31 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_signquiz_signquizquestion_signquiz_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signquizquestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='signquizquestion',
            name='question',
        ),
        migrations.DeleteModel(
            name='SignQuiz',
        ),
        migrations.DeleteModel(
            name='SignQuizQuestion',
        ),
    ]
