# Generated by Django 5.1.7 on 2025-03-31 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_remove_signquizquestion_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.level')),
                ('questions', models.ManyToManyField(to='adminapp.question')),
            ],
        ),
    ]
