# Generated by Django 5.1.7 on 2025-03-31 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_signquiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signquiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='signquiz',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signquiz',
            name='surveys',
            field=models.ManyToManyField(to='adminapp.survey'),
        ),
        migrations.AddField(
            model_name='signquiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='signquiz',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Quiz Title'),
        ),
    ]
