# Generated by Django 5.1.7 on 2025-03-31 09:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_alter_signquiz_options_signquiz_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signquiz',
            options={},
        ),
        migrations.RemoveField(
            model_name='signquiz',
            name='category',
        ),
        migrations.RemoveField(
            model_name='signquiz',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='signquiz',
            name='surveys',
        ),
        migrations.RemoveField(
            model_name='signquiz',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='signquiz',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='signquiz',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='adminapp.level'),
        ),
        migrations.AlterField(
            model_name='signquiz',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Quiz Title'),
        ),
        migrations.CreateModel(
            name='SignQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='adminapp.signquiz')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('quiz', 'question')},
            },
        ),
    ]
