# Generated by Django 5.1.7 on 2025-03-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_useranswer_userprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
