# Generated by Django 5.1.7 on 2025-04-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_useranswer_userlevelprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
